### PR TITLE
Update for Starscream 4

### PR DESCRIPTION
**Pull request by JetForMe**
A proposed fix for https://github.com/davidstump/SwiftPhoenixClient/issues/184

I updated the package manifest to point to Starscream 4.0.0<4.1, and updated the affected files. The one place where I'm not sure I handled things correctly is in `StarscreamTransport.swift`, where the delegate methods have changed into a single `didReceive(event:client:)` call. The events weren't a direct mapping to the previous callbacks. In particular, I didn't know what error code to pass to `onClose(code:)`.

I also accidentally left the old code in the file, albeit commented out. I would've changed it, but I had to create a 2.0.1 tag to get Xcode to pick up my changes, and didn't want to make another tag for the new commit (not sure if there's a way to re-assign the tag; my git-fu is basic).

### CODE REVIEW

**Comment by dsrees** [comment]
Im sorry I haven't gotten the chance to review this. It would be helpful if you could test this yourself against the instructions commented here: https://github.com/davidstump/SwiftPhoenixClient/blob/master/Examples/Basic/basic/BasicChatViewController.swift#L14

I use this project as a local server to test against: https://github.com/chrismccord/phoenix_chat_example

**Comment by JetForMe** [comment]
I'm sorry, I'm swamped with a deadline for the next several weeks. I made this change and got it working for us, but you'll probably have to do whatever you need to to make the packages compatible.

**Comment by dsrees** [comment]
👍🏼 Understood

**Comment by dsrees** [comment]
I will not be updating SwiftPhoenixClient to starscream 4.x since the project hasn't seen much maintenance recently and there are known issues with 4.x that are not being addressed.

3.x has been around for a long time and has relatively few issues.

**Pull request closed without merging**
