### PR TITLE
Removed external json lib and replaced it with native ios parsing

### PR DESCRIPTION
**Pull request by NilsLattek**
Fixes the issues mentioned in #48 
This should also allow libraries like SwiftyJSON or Gloss to parse ```Phoenix.Message.message```.

### CODE REVIEW

**Comment by davidstump** [comment]
Wow - thanks for the quick PR! <3

I'll check it out as soon as I can and get it merged.

Cheers.

**Comment by NilsLattek** [comment]
You're welcome, take your time, I am going to use my branch in the meantime 😄

**Comment by BryanJBryce** [comment]
@NilsLattek Don't forget Marshal, Swifty is not very swift: https://github.com/bwhiteley/JSONShootout

**Comment by NilsLattek** [comment]
Any parsing library which accepts a dictionary or array from ```NSJSONSerialization.JSONObjectWithData``` should work. Looking at the JSONShootout examples this should work.

**Comment by davidstump** [comment]
I went ahead and tested the Swift 3 updates and pushed them to master to fast track getting this library working with the current versions. Unfortunately this is going to cause a few issues with the native json parsing in this PR. I can look at updating it when I have a few mins, but would appreciate it if you happen to have some time to update the PR to the new syntax.

Thanks as always!

**Comment by NilsLattek** [comment]
Puuh too many merge conflicts when I try to merge master into this branch. I guess it would make sense to delete the branch/PR and reapply the changes to master.
I might have a look in the next weeks, but I am also quite busy with upgrading swift version in my projects...

**Pull request closed without merging**
