### PR TITLE
Support token authentication #9

### PR DESCRIPTION
**Pull request by aaa707**
Hi there,

I've changed to support token authentication.

It's a very simple change.
So I'm not sure it's ok, but you can use toke auth like this:

```swift
override func viewDidLoad() {
    super.viewDidLoad()

    let socket = Phoenix.Socket(domainAndPort: "localhost:4000", path: "socket", transport: "websocket?userToken=<user token>")
    let topic = "rooms:lobby"
    socket.join(topic: topic, message: Phoenix.Message(message: ["roomToken": "<room token>"])) { channel in
        let chan = channel as! Phoenix.Channel

        chan.on("join") { message in
          print("You joined the room.")
        }
    }
}
```

### CODE REVIEW

**Comment by tehprofessor** [comment]
This would fix the issue I just created #23

**Comment by sjrmanning** [comment]
:+1:, I've had to fork to do the same and would appreciate this being pulled in!

**Comment by davidstump** [comment]
:+1: Sorry for the delay

**Comment by tehprofessor** [comment]
Woo-hoo! Thanks @davidstump

**Comment by davidkuhta** [comment]
Just a note, tokens generated by `Phoenix.Token` can include `=`, which will result in nil errors when `Phoenix.Socket` calls `reconnect` as they won't all for construction of valid NSURLs.
Specifically:
```
 self.conn = WebSocket(url: NSURL(string: self.endPoint!)!)
```

**Pull request merged**
