### PR TITLE
Updated CocoaPods, Starscream and added support for Query Params

### PR DESCRIPTION
**Pull request by bAmpT**
When authenticating, you need to be able to send a token:
Request: GET /socket/websocket?userToken=

### CODE REVIEW

**Comment by davidstump** [comment]
Thanks!! <3 

Life is a little hectic at the moment, but I will pull this down and get it added to the next release.

Thanks again, much appreciated!

**Comment by NilsLattek** [comment]
Isn't this already possible? I am using the following way to send my guardian token for authentication and it works:
```elixir
Phoenix.Socket(domainAndPort: "localhost", path: "socket", transport: "websocket?guardian_token=\(token)")
```

**Comment by bAmpT** [comment]
Ah yes that should be possible as well, but the query parameter is a cleaner way. But there is no way to add custom headers right?

**Comment by davidstump** [comment]
Thanks a ton for the contributions. The dependencies and query params were updated in other commits separately. I sincerely appreciate the code and interest :D

**Pull request closed without merging**
